version: '2'
services:
    activityserver-app:
        image: activityserver
        external_links:
            - activityserver-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=activityserver
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    activityserver-mongodb:
        extends:
            file: mongodb.yml
            service: activityserver-mongodb
