version: '2'
services:
    activityserver-mongodb:
        container_name: activityserver-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/activityserver/mongodb/:/data/db/
